---

- name: Check chrome installed or not
  ansible.builtin.command: which google-chrome
  failed_when: false
  changed_when: false
  check_mode: false
  register: chrome_present

- name: Install chrome from debian package
  ansible.builtin.apt:
    deb: "{{ chrome_url }}"
  when: chrome_present.rc == 1

- name: apt autoclean
  ansible.builtin.apt:
    autoclean: true

- name: apt autoremove
  ansible.builtin.apt:
    autoremove: true
