---

- name: if Docker is already installed?.
  command: which docker
  failed_when: false
  changed_when: false
  check_mode: false
  register: docker_present

- name: Download Docker install script.
  get_url:
    url: https://get.docker.com/
    dest: /tmp/get-docker.sh
    mode: 0775
  when: 
    - docker_present.rc == 1

- name: Run Docker install script.
  command: /tmp/get-docker.sh
  environment:
    CHANNEL: stable
  when: 
    - docker_present.rc == 1

- name: Start docker
  service:
    name: docker
    state: started
    enabled: true

- name: Create group docker
  group:
    name: docker
    state: present

- name: adding existing user '{{ ansible_user }}' to group sudo
  user:
    name: '{{ ansible_user }}'
    groups: docker
    append: yes

- name: Reset connection
  meta: reset_connection